export const actions = {
    FETCH_SETTINGS: 'FETCH_SETTINGS',
    UPDATE_SETTING: 'UPDATE_SETTING',
    SET_DEFAULT_SETTINGS: 'SET_DEFAULT_SETTINGS',
    ADD_CONTENT_SCORE: 'ADD_CONTENT_SCORE',
    FETCH_CONTENT_SCORE: 'FETCH_CONTENT_SCORE',
}

export default actions;