export const actions = {
    FETCH_ALL_ARTICLES: "FETCH_ALL_ARTICLES",
    REFRESH_ARTICLES: "REFRESH_ARTICLES",
    SEARCH_ARTICLES: "SEARCH_ARTICLES",
    FETCH_STORIES: "FETCH_STORIES",
    UPDATE_ARTICLES_VIEW: "UPDATE_ARTICLES_VIEW",
}

export default actions;