export const actions = {
    FETCH_ALL_ARTICLES: "FETCH_ALL_ARTICLES",
    FETCH_ALL_ARTICLES_OF_TOPIC: "FETCH_ALL_ARTICLES_OF_TOPIC",
    REFRESH_ARTICLES: "REFRESH_ARTICLES",
    REFRESH_ARTICLES_OF_TOPIC: "REFRESH_ARTICLES_OF_TOPIC",
    SEARCH_ARTICLES: "SEARCH_ARTICLES",
    FETCH_STORIES: "FETCH_STORIES",
    UPDATE_ARTICLES_VIEW: "UPDATE_ARTICLES_VIEW",
    SAVE_ARTICLE_STATE: "SAVE_ARTICLE_STATE",
    FETCH_ARTICLES_STATE: "FETCH_ALL_ARTICLES_STATE",
}

export default actions;